variables:
  IMAGE: ubuntu:with-hermitcore
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage build
##############################################################################
build:
  stage: build
  script:
    - make all
    - make release=1 all
  image: ${IMAGE}
  cache:
    paths:
      - target/x86_64-unknown-hermit-kernel
      - examples/target/x86_64-unknown-hermit
      - loader/target/x86_64-unknown-hermit-loader
    key: build
  artifacts:
    paths:
      - target/x86_64-unknown-hermit-kernel
      - examples/target/x86_64-unknown-hermit
      - loader/target/x86_64-unknown-hermit-loader
  tags:
    - docker

# Stage: test:tarpaulin
##############################################################################
test:tarpaulin:
  stage: test
  script:
    - rm -rf examples loader
    - cargo tarpaulin -v
  image: ${IMAGE}
  tags:
    - docker

# Stage: test:cargo
##############################################################################
test:cargo:
  stage: test
  script: 
    - cargo test --lib
  image: ${IMAGE}
  tags:
    - docker

# Stage: test
##############################################################################

test:uhyve:
  stage: test
  script:
    - git clone --depth 1 -b path2rs https://github.com/hermitcore/hermit-caves.git caves
    - cd caves
    - mkdir build
    - cd build
    - cmake ..
    - make
    - HERMIT_VERBOSE=1 ./proxy ../../examples/target/x86_64-unknown-hermit/debug/hctests
    - HERMIT_VERBOSE=1 ./proxy ../../examples/target/x86_64-unknown-hermit/release/hctests
  image: ${IMAGE}
  dependencies:
    - build
  tags:
    - docker
