variables:
  IMAGE: ubuntu:with-hermitcore
  FINAL: rwthos/hermitcore-rs
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage build
##############################################################################
build:
  stage: build
  script:
    - cargo build -Z build-std=core,alloc --target x86_64-unknown-hermit-kernel
    - cargi build -Z build-std=core,alloc --target x86_64-unknown-hermit-kernel --release
  image: ${IMAGE}
  cache:
    paths:
      - target/x86_64-unknown-hermit-kernel
    key: build
  artifacts:
    paths:
      - target/x86_64-unknown-hermit-kernel
  tags:
    - docker

# Stage: test

##############################################################################
#test:tarpaulin:
#  stage: test
#  script:
#    - rm -rf tests loader
#    - cargo tarpaulin -v --exclude-files src/arch/aarch64
#  image: ${IMAGE}
#  tags:
#    - docker

test:cargo:
  stage: test
  script: 
    - cargo test --target x86_64-unknown-linux-gnu
  image: ${IMAGE}
  tags:
    - docker
