variables:
  IMAGE: ubuntu:with-hermitcore
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage build
build:
  stage: build
  script:
    - make
    - make release=1
  image: ${IMAGE}
  tags:
    - docker

# Stage: test:cargotest
##############################################################################
test:cargo:
  stage: test
  script: 
    - cargo test --lib
  image: ${IMAGE}
  tags:
    - docker

# Stage: test
##############################################################################

test:uhyve:
  stage: test
  script:
    - make
    - make release=1
    - git clone --depth 1 -b path2rs https://github.com/hermitcore/hermit-caves.git caves
    - cd caves
    - mkdir build
    - cd build
    - cmake ..
    - make
    - HERMIT_VERBOSE=1 ./proxy ../../examples/target/x86_64-unknown-hermit/debug/hctests
    - HERMIT_VERBOSE=1 ./proxy ../../examples/target/x86_64-unknown-hermit/release/hctests
  image: ${IMAGE}
  dependencies:
    - build
  tags:
    - docker
