[package]
name = "hctests"
version = "0.1.0"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
edition = "2018"
publish = false

[dependencies]
rayon = { git = "https://github.com/hermitcore/rayon.git" }
